version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Wstoytwhi@123}
      POSTGRES_DB: ${POSTGRES_DB:-tracker}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracker_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      # NextAuth URLs
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=fallback-secret-for-docker-compose-only
      # The database url inside docker network needs to point to the 'db' service mapped port
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-Wstoytwhi@123}@db:5432/${POSTGRES_DB:-tracker}?schema=public
    depends_on:
      db:
        condition: service_healthy
    # We mount the DB migration command to automatically sync prisma on boot up
    command: >
      sh -c "npx prisma db push && HOSTNAME='0.0.0.0' node server.js"

volumes:
  postgres_data:
